#!/usr/bin/env python3
"""Dump the real Glaxnimate Python API to docs/glaxnimate-api.md.

The published docs at glaxnimate.org are a version behind the bindings we build
from source (they still show `document.main`, which no longer exists). Ground
the project on what the module actually exposes, not on what the docs claim.

Usage:  .venv/bin/python scripts/introspect_api.py
"""

from __future__ import annotations

import inspect
from pathlib import Path

import glaxnimate
from glaxnimate import environment, io, model

OUT = Path(__file__).resolve().parent.parent / "docs" / "glaxnimate-api.md"

SKIP = {"find_by_name", "find_by_type_name", "find_by_uuid", "get", "has",
        "grouped_animations", "object_name", "stretch_time", "users", "uuid",
        "type_name", "type_name_human", "document"}


def members(obj) -> list[str]:
    return sorted(m for m in dir(obj) if not m.startswith("_") and m not in SKIP)


def shape_types() -> list[str]:
    """The string names accepted by Composition.add_shape()."""
    return sorted(
        n for n in dir(model.shapes)
        if not n.startswith("_") and inspect.isclass(getattr(model.shapes, n))
    )


def main() -> None:
    lines: list[str] = []
    w = lines.append

    w("# Glaxnimate Python API — as actually built\n")
    w("Generated by `scripts/introspect_api.py` from the source-built bindings.")
    w("**The online docs are out of date** — prefer this file.\n")

    w("## Gotchas (each of these silently wastes an hour)\n")
    w("- `Document` has **no** `.main`. Compositions come from "
      "`doc.assets.add_composition()`.")
    w("- `render_image(frame)` is on **Composition**, not Document. It returns a "
      "`PIL.Image` (RGBA).")
    w("- **`Layer.animation.last_frame` defaults to `-1`**, which makes the layer "
      "invisible. Set it or every frame renders blank — with no error.")
    w("- `io.registry.from_extension(ext, io.Direction.Export)` needs the "
      "direction; `save()` takes a **Composition**, not a Document.")
    w("- On an IO format, `fmt.name` is a **property** but `fmt.extensions()` is a "
      "**method**. Mixing them up is a `TypeError`.")
    w("- Rendering at exactly `last_frame` yields an empty image (the range is "
      "exclusive at the end).\n")

    w("## Minimal working example\n")
    w("```python")
    w("from glaxnimate import model, utils, environment, io")
    w("")
    w("with environment.Headless():")
    w('    doc = model.Document("")')
    w("    comp = doc.assets.add_composition()")
    w("    comp.width, comp.height = 640, 480")
    w("    comp.animation.last_frame = 60")
    w("")
    w('    lay = comp.add_shape("Layer")')
    w("    lay.animation.first_frame = 0")
    w("    lay.animation.last_frame = 60      # REQUIRED: defaults to -1")
    w("")
    w('    lay.add_shape("Fill").color.value = "#e33"   # applies to *following* shapes')
    w('    ball = lay.add_shape("Ellipse")')
    w("    ball.size.value = utils.Size(80, 80)")
    w("    ball.position.set_keyframe(0,  utils.Point(100, 400))")
    w("    ball.position.set_keyframe(30, utils.Point(320, 120))")
    w("")
    w("    img = comp.render_image(30)        # -> PIL.Image RGBA")
    w('    fmt = io.registry.from_extension("json", io.Direction.Export)')
    w("    data = fmt.save(comp)              # -> bytes (Lottie)")
    w("```\n")

    w("## Modules\n")
    w("`" + "`, `".join(m for m in dir(glaxnimate) if not m.startswith("_")) + "`\n")

    w("## Shape type names for `add_shape(...)`\n")
    w("`" + "`, `".join(shape_types()) + "`\n")

    with environment.Headless():
        doc = model.Document("")
        comp = doc.assets.add_composition()
        lay = comp.add_shape("Layer")

        w("## Key classes\n")
        for label, obj in [
            ("Document", doc),
            ("Assets (doc.assets)", doc.assets),
            ("Composition", comp),
            ("Composition.animation", comp.animation),
            ("Layer", lay),
            ("Layer.animation", lay.animation),
            ("Layer.transform", lay.transform),
        ]:
            w(f"### {label}\n")
            w("`" + "`, `".join(members(obj)) + "`\n")

        # `fmt.extensions(direction)` is a Qt slot and the Direction enum does not
        # marshal from Python, so probe the registry by extension instead — which
        # is the question we actually care about.
        w("## IO — probed by extension\n")
        w("| ext | import | export |")
        w("|---|---|---|")
        candidates = ["rawr", "json", "lottie", "tgs", "svg", "svgz", "gif", "webp",
                      "png", "jpg", "mp4", "webm", "avi", "riv", "aep", "ai", "sif"]
        for ext in candidates:
            row = []
            for d in (io.Direction.Import, io.Direction.Export):
                try:
                    fmt = io.registry.from_extension(ext, d)
                    row.append(fmt.name if fmt else "—")
                except Exception:
                    row.append("—")
            if row != ["—", "—"]:
                w(f"| `.{ext}` | {row[0]} | {row[1]} |")
        w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
